---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Template CF para construir a infraestrura
  do ECS Cluster
Parameters:
  ECSClusterName:
    Type: String

  ECSClusterService:
    Type: String

  GraphQLECSSecurityGroup:
    Type: String

  CpuTask:
    Type: Number

  MemoryTask:
    Type: Number

  ContainerPort:
    Type: Number

  ImageUri:
    Type: String

Resources:
  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Ref ECSClusterName
      CapacityProviders:
        - FARGATE
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Tags:
        - Key: Project
          Value: GraphQL

  GraphQLECSSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue MinhaVPC
      GroupName: !Ref GraphQLECSSecurityGroup
      GroupDescription: "GraphQL ECS Security Group"
      SecurityGroupIngress:
        - CidrIp: 10.0.0.1/16
          FromPort: 80
          ToPort: 8080
          IpProtocol: tcp
      Tags:
        - Key: Project
          Value: GraphQL
        - Key: Name
          Value: "sg-ecs-graphql"

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: graphql-log-group
      RetentionInDays: 1

  GraphQLClusterService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Ref ECSClusterService
      LaunchType: FARGATE
      PlatformVersion: "1.4.0"
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      HealthCheckGracePeriodSeconds: 60
      TaskDefinition: !Ref TaskDefinition
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      LoadBalancers:
        - ContainerName: !Ref AWS::StackName
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !ImportValue GraphQLTargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - !ImportValue SubnetPrivadaA
            - !ImportValue SubnetPrivadaB
          SecurityGroups:
            - !Ref GraphQLECSSG

  # Task Definition
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      NetworkMode: "awsvpc"
      RequiresCompatibilities:
        - FARGATE
      Cpu: !Ref CpuTask
      Memory: !Ref MemoryTask
      TaskRoleArn: !GetAtt TaskRole.Arn
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: !Ref AWS::StackName
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ImageUri}"
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: "service"

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/graphql/ecs/"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ecs-tasks.amazonaws.com"
            Action:
              - "sts:AssumeRole"

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/graphql/ecs/"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ec2.amazonaws.com"
                - "ecs-tasks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

Outputs:
  ECSClusterArn:
    Description: Exports the Arn value of the ECS Cluster
    Value: !GetAtt ECSCluster.Arn