---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Template CF para construir a infraestrura
  ECR
Parameters:
  RepositoryName:
    Type: String

Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      ImageScanningConfiguration:
        ScanOnPush: true
      Tags:
      - Key: Project
        Value: GraphQL

Outputs:
  ECRRepoName:
    Description: Container Repository
    Value: !Ref Repository